/* =========================================================
   AI OR HUMAN DETECTOR
   AND NATURAL WRITING EDITOR
========================================================= */


/* =========================================================
   AI-STYLE PHRASES

   These are only linguistic signals.
   They are NOT proof that text was generated by AI.
========================================================= */

const AI_PHRASES = [

    "in conclusion",

    "it is important to note",

    "it is worth noting",

    "delve into",

    "comprehensive",

    "furthermore",

    "moreover",

    "in today's world",

    "plays a crucial role",

    "plays an important role",

    "this article aims to",

    "in summary",

    "overall",

    "let us explore",

    "a testament to",

    "seamless integration",

    "in the modern world",

    "in the rapidly evolving",

    "it can be seen that",

    "it is essential to understand",

    "one of the key factors",

    "another important aspect",

    "in other words"

];


/* =========================================================
   DOM ELEMENTS
========================================================= */

const textInput =
    document.getElementById(
        "textInput"
    );


const wordCount =
    document.getElementById(
        "wordCount"
    );


const characterCount =
    document.getElementById(
        "characterCount"
    );


const analyzeButton =
    document.getElementById(
        "analyzeButton"
    );


const humanizeButton =
    document.getElementById(
        "humanizeButton"
    );


const clearButton =
    document.getElementById(
        "clearButton"
    );


const loading =
    document.getElementById(
        "loading"
    );


const errorBox =
    document.getElementById(
        "errorBox"
    );


const resultSection =
    document.getElementById(
        "resultSection"
    );


const humanizedSection =
    document.getElementById(
        "humanizedSection"
    );


const humanizedText =
    document.getElementById(
        "humanizedText"
    );


const copyButton =
    document.getElementById(
        "copyButton"
    );


const useHumanizedButton =
    document.getElementById(
        "useHumanizedButton"
    );


/* =========================================================
   WORD COUNT
========================================================= */

function countWords(text) {

    if (!text.trim()) {

        return 0;

    }


    /*
       Unicode-aware word matching.

       Supports English and many other
       Unicode writing systems.
    */

    const matches =
        text.match(
            /[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu
        );


    return matches
        ? matches.length
        : 0;

}


/* =========================================================
   TOKENIZE TEXT
========================================================= */

function tokenize(text) {

    const matches =
        text
            .toLowerCase()
            .match(
                /[\p{L}\p{N}]+(?:['’-][\p{L}\p{N}]+)*/gu
            );


    return matches || [];

}


/* =========================================================
   GET SENTENCES
========================================================= */

function getSentences(text) {

    return text
        .split(/[.!?]+/)
        .map(
            sentence =>
                sentence.trim()
        )
        .filter(
            sentence =>
                sentence.length > 0
        );

}


/* =========================================================
   AVERAGE
========================================================= */

function average(numbers) {

    if (
        numbers.length === 0
    ) {

        return 0;

    }


    return (
        numbers.reduce(
            (sum, value) =>
                sum + value,
            0
        )
        /
        numbers.length
    );

}


/* =========================================================
   STANDARD DEVIATION
========================================================= */

function standardDeviation(numbers) {

    if (
        numbers.length === 0
    ) {

        return 0;

    }


    const avg =
        average(numbers);


    const variance =
        average(
            numbers.map(
                number =>
                    Math.pow(
                        number - avg,
                        2
                    )
            )
        );


    return Math.sqrt(
        variance
    );

}


/* =========================================================
   SENTENCE LENGTHS
========================================================= */

function getSentenceLengths(
    sentences
) {

    return sentences.map(
        sentence =>
            countWords(sentence)
    );

}


/* =========================================================
   VOCABULARY RATIO
========================================================= */

function vocabularyRatio(
    tokens
) {

    if (
        tokens.length === 0
    ) {

        return 0;

    }


    const uniqueWords =
        new Set(tokens);


    return (
        uniqueWords.size /
        tokens.length
    );

}


/* =========================================================
   REPETITION RATIO
========================================================= */

function repetitionRatio(
    tokens
) {

    if (
        tokens.length === 0
    ) {

        return 0;

    }


    const frequencies =
        new Map();


    for (
        const word of tokens
    ) {

        frequencies.set(
            word,
            (
                frequencies.get(
                    word
                ) || 0
            ) + 1
        );

    }


    let repeatedWords = 0;


    for (
        const frequency
        of frequencies.values()
    ) {

        if (
            frequency > 1
        ) {

            repeatedWords +=
                frequency - 1;

        }

    }


    return (
        repeatedWords /
        tokens.length
    );

}


/* =========================================================
   AI PHRASE DETECTION
========================================================= */

function findAIPhrases(text) {

    const lowerText =
        text.toLowerCase();


    let hits = 0;


    const found = [];


    for (
        const phrase
        of AI_PHRASES
    ) {

        let position = 0;

        let phraseCount = 0;


        while (true) {

            const index =
                lowerText.indexOf(
                    phrase,
                    position
                );


            if (
                index === -1
            ) {

                break;

            }


            phraseCount++;


            position =
                index +
                phrase.length;

        }


        if (
            phraseCount > 0
        ) {

            hits +=
                phraseCount;


            found.push({

                phrase:
                    phrase,

                count:
                    phraseCount

            });

        }

    }


    return {

        hits:
            hits,

        found:
            found

    };

}


/* =========================================================
   FIRST-PERSON COUNT
========================================================= */

function firstPersonCount(text) {

    const matches =
        text
            .toLowerCase()
            .match(
                /\b(i|i'm|i’ve|i'd|my|me|we|our|us)\b/g
            );


    return matches
        ? matches.length
        : 0;

}


/* =========================================================
   CONTRACTION COUNT
========================================================= */

function contractionCount(text) {

    const matches =
        text.match(
            /\b[\p{L}]+(?:['’][\p{L}]+)\b/gu
        );


    return matches
        ? matches.length
        : 0;

}


/* =========================================================
   PUNCTUATION COUNT
========================================================= */

function punctuationCount(text) {

    const matches =
        text.match(
            /[,;:—–-]/g
        );


    return matches
        ? matches.length
        : 0;

}


/* =========================================================
   PARAGRAPH COUNT
========================================================= */

function paragraphCount(text) {

    const paragraphs =
        text
            .split(
                /\n\s*\n/
            )
            .filter(
                paragraph =>
                    paragraph.trim()
                        .length > 0
            );


    /*
       If there is text but no blank line,
       count it as one paragraph.
    */

    if (
        paragraphs.length === 0 &&
        text.trim().length > 0
    ) {

        return 1;

    }


    return paragraphs.length;

}


/* =========================================================
   FEATURE EXTRACTION
========================================================= */

function extractFeatures(text) {

    const tokens =
        tokenize(text);


    const sentences =
        getSentences(text);


    const lengths =
        getSentenceLengths(
            sentences
        );


    const avgSentenceLength =
        average(lengths);


    const deviation =
        standardDeviation(
            lengths
        );


    /*
       Sentence-length variation.

       This is only one weak signal.
    */

    const burstiness =
        avgSentenceLength > 0

            ? deviation /
              avgSentenceLength

            : 0;


    const vocabulary =
        vocabularyRatio(
            tokens
        );


    const repetition =
        repetitionRatio(
            tokens
        );


    const aiPhrases =
        findAIPhrases(
            text
        );


    const firstPerson =
        firstPersonCount(
            text
        );


    const contractions =
        contractionCount(
            text
        );


    const punctuation =
        punctuationCount(
            text
        );


    return {

        wordCount:
            tokens.length,

        characterCount:
            text.length,

        sentenceCount:
            sentences.length,

        paragraphCount:
            paragraphCount(
                text
            ),

        averageSentenceLength:
            avgSentenceLength,

        burstiness:
            burstiness,

        vocabularyRatio:
            vocabulary,

        repetitionRatio:
            repetition,

        aiPhraseHits:
            aiPhrases.hits,

        firstPersonCount:
            firstPerson,

        contractionCount:
            contractions,

        punctuationCount:
            punctuation

    };

}


/* =========================================================
   DETECTION ALGORITHM
========================================================= */

function detectText(text) {

    const features =
        extractFeatures(
            text
        );


    /*
       Start at neutral.
    */

    let score = 50;


    /* -----------------------------------------
       SENTENCE VARIATION
    ----------------------------------------- */

    if (
        features.burstiness <
        0.35
    ) {

        score += 12;

    }

    else if (
        features.burstiness >
        0.85
    ) {

        score -= 10;

    }


    /* -----------------------------------------
       VOCABULARY
    ----------------------------------------- */

    if (
        features.vocabularyRatio >
        0.72
    ) {

        score += 5;

    }

    else if (
        features.vocabularyRatio <
        0.50
    ) {

        score -= 4;

    }


    /* -----------------------------------------
       AI-STYLE PHRASES
    ----------------------------------------- */

    score += Math.min(
        features.aiPhraseHits * 2.5,
        15
    );


    /* -----------------------------------------
       REPETITION
    ----------------------------------------- */

    score += Math.min(
        features.repetitionRatio * 20,
        8
    );


    /* -----------------------------------------
       FIRST PERSON
    ----------------------------------------- */

    const firstPersonRatio =
        features.wordCount > 0

            ? features.firstPersonCount /
              features.wordCount

            : 0;


    score -= Math.min(
        firstPersonRatio * 80,
        10
    );


    /* -----------------------------------------
       CONTRACTIONS
    ----------------------------------------- */

    const contractionRatio =
        features.wordCount > 0

            ? features.contractionCount /
              features.wordCount

            : 0;


    score -= Math.min(
        contractionRatio * 100,
        8
    );


    /* -----------------------------------------
       LIMIT RESULT
    ----------------------------------------- */

    score =
        Math.max(
            1,
            Math.min(
                99,
                Math.round(score)
            )
        );


    /* -----------------------------------------
       RESULT LABEL
    ----------------------------------------- */

    let label;

    let confidence;


    if (
        score >= 65
    ) {

        label =
            "Likely AI-assisted";


        confidence =
            score;

    }

    else if (
        score <= 35
    ) {

        label =
            "Likely human-written";


        confidence =
            100 - score;

    }

    else {

        label =
            "Uncertain / mixed";


        confidence =
            50 +
            Math.abs(
                score - 50
            );

    }


    return {

        aiProbability:
            score,

        humanProbability:
            100 - score,

        label:
            label,

        confidence:
            Math.round(
                confidence
            ),

        features:
            features

    };

}


/* =========================================================
   FORMAT NUMBERS
========================================================= */

function formatNumber(number) {

    return number.toLocaleString();

}


/* =========================================================
   DISPLAY STATISTICS
========================================================= */

function displayStatistics(
    features
) {

    const statistics =
        document.getElementById(
            "statistics"
        );


    const stats = [

        [
            "Words",
            formatNumber(
                features.wordCount
            )
        ],

        [
            "Characters",
            formatNumber(
                features.characterCount
            )
        ],

        [
            "Sentences",
            formatNumber(
                features.sentenceCount
            )
        ],

        [
            "Paragraphs",
            formatNumber(
                features.paragraphCount
            )
        ],

        [
            "Average sentence length",
            features
                .averageSentenceLength
                .toFixed(2)
        ],

        [
            "Sentence variation",
            features
                .burstiness
                .toFixed(3)
        ],

        [
            "Vocabulary ratio",
            features
                .vocabularyRatio
                .toFixed(3)
        ],

        [
            "Repeated-word ratio",
            features
                .repetitionRatio
                .toFixed(3)
        ],

        [
            "AI-style phrase hits",
            formatNumber(
                features.aiPhraseHits
            )
        ],

        [
            "Personal-word count",
            formatNumber(
                features.firstPersonCount
            )
        ]

    ];


    statistics.innerHTML = "";


    for (
        const [label, value]
        of stats
    ) {

        const div =
            document.createElement(
                "div"
            );


        div.className =
            "stat";


        const labelElement =
            document.createElement(
                "span"
            );


        labelElement.className =
            "stat-label";


        labelElement.textContent =
            label;


        const valueElement =
            document.createElement(
                "span"
            );


        valueElement.className =
            "stat-value";


        valueElement.textContent =
            value;


        div.appendChild(
            labelElement
        );


        div.appendChild(
            valueElement
        );


        statistics.appendChild(
            div
        );

    }

}


/* =========================================================
   DISPLAY DETECTION RESULT
========================================================= */

function displayResult(
    result
) {

    const score =
        result.aiProbability;


    const human =
        result.humanProbability;


    /* -----------------------------------------
       SCORE
    ----------------------------------------- */

    document.getElementById(
        "aiScore"
    ).textContent =
        `${score}%`;


    /* -----------------------------------------
       LABEL
    ----------------------------------------- */

    document.getElementById(
        "resultTitle"
    ).textContent =
        result.label;


    /* -----------------------------------------
       CONFIDENCE
    ----------------------------------------- */

    document.getElementById(
        "confidenceText"
    ).textContent =
        `Confidence: ${result.confidence}%`;


    /* -----------------------------------------
       AI PERCENTAGE
    ----------------------------------------- */

    document.getElementById(
        "aiPercentage"
    ).textContent =
        `${score}%`;


    /* -----------------------------------------
       HUMAN PERCENTAGE
    ----------------------------------------- */

    document.getElementById(
        "humanPercentage"
    ).textContent =
        `${human}%`;


    /* -----------------------------------------
       AI PROGRESS BAR
    ----------------------------------------- */

    document.getElementById(
        "aiProgress"
    ).style.width =
        `${score}%`;


    /* -----------------------------------------
       HUMAN PROGRESS BAR
    ----------------------------------------- */

    document.getElementById(
        "humanProgress"
    ).style.width =
        `${human}%`;


    /* -----------------------------------------
       SCORE CIRCLE
    ----------------------------------------- */

    const degrees =
        score * 3.6;


    document.getElementById(
        "scoreCircle"
    ).style.background = `

        conic-gradient(

            #7182ff
            ${degrees}deg,

            #293451
            ${degrees}deg

        )

    `;


    /* -----------------------------------------
       STATISTICS
    ----------------------------------------- */

    displayStatistics(
        result.features
    );


    /* -----------------------------------------
       SHOW RESULT
    ----------------------------------------- */

    resultSection.classList.remove(
        "hidden"
    );

}


/* =========================================================
   ANALYZE BUTTON
========================================================= */

analyzeButton.addEventListener(
    "click",
    function() {

        const text =
            textInput.value.trim();


        /* -------------------------------------
           EMPTY TEXT
        ------------------------------------- */

        if (
            !text
        ) {

            showError(
                "Please enter some text."
            );

            return;

        }


        /* -------------------------------------
           MINIMUM WORDS
        ------------------------------------- */

        const words =
            countWords(
                text
            );


        if (
            words < 20
        ) {

            showError(
                "Please enter at least 20 words for a more meaningful estimate."
            );

            return;

        }


        /* -------------------------------------
           RESET
        ------------------------------------- */

        errorBox.classList.add(
            "hidden"
        );


        resultSection.classList.add(
            "hidden"
        );


        /* -------------------------------------
           LOADING
        ------------------------------------- */

        loading.classList.remove(
            "hidden"
        );


        /*
           Small timeout lets the loading
           animation render before processing.
        */

        setTimeout(
            function() {

                try {

                    const result =
                        detectText(
                            text
                        );


                    displayResult(
                        result
                    );

                }

                catch (error) {

                    console.error(
                        error
                    );


                    showError(
                        "Something went wrong while analyzing the text."
                    );

                }


                finally {

                    loading.classList.add(
                        "hidden"
                    );

                }

            },
            50
        );

    }
);


/* =========================================================
   FORMAL → NATURAL WORD DICTIONARY
========================================================= */

const naturalReplacements = {

    "utilize": "use",

    "utilizes": "uses",

    "utilized": "used",

    "commence": "start",

    "commenced": "started",

    "approximately": "about",

    "numerous": "many",

    "demonstrate": "show",

    "demonstrates": "shows",

    "demonstrated": "showed",

    "facilitate": "help",

    "facilitates": "helps",

    "obtain": "get",

    "subsequently": "later",

    "therefore": "so",

    "additionally": "also",

    "sufficient": "enough",

    "assistance": "help",

    "individuals": "people",

    "individual": "person",

    "regarding": "about",

    "endeavor": "try",

    "endeavors": "tries",

    "prior to": "before",

    "in order to": "to",

    "due to the fact that": "because",

    "a significant number of": "many",

    "at this point in time": "now",

    "in the event that": "if",

    "for the purpose of": "to",

    "with regard to": "about",

    "in addition to": "besides",

    "is able to": "can",

    "are able to": "can",

    "has the ability to": "can"

};


/* =========================================================
   ESCAPE REGEX
========================================================= */

function escapeRegExp(
    text
) {

    return text.replace(
        /[.*+?^${}()|[\]\\]/g,
        "\\$&"
    );

}


/* =========================================================
   REPLACE FORMAL WORDS
========================================================= */

function replaceFormalWords(
    text
) {

    const replacements =
        Object.entries(
            naturalReplacements
        ).sort(
            (a, b) =>
                b[0].length -
                a[0].length
        );


    for (
        const [formal, natural]
        of replacements
    ) {

        const regex =
            new RegExp(
                `\\b${escapeRegExp(formal)}\\b`,
                "gi"
            );


        text =
            text.replace(
                regex,
                function(match) {

                    /*
                       Preserve the first-letter
                       capitalization.
                    */

                    if (
                        match[0] ===
                        match[0].toUpperCase()
                    ) {

                        return (
                            natural
                                .charAt(0)
                                .toUpperCase()
                            +
                            natural.slice(1)
                        );

                    }


                    return natural;

                }
            );

    }


    return text;

}


/* =========================================================
   CLEAN SPACING
========================================================= */

function cleanSpacing(
    text
) {

    return text

        .replace(
            /[ \t]+/g,
            " "
        )

        .replace(
            / +([,.!?;:])/g,
            "$1"
        )

        .replace(
            /([,.!?;:])([A-Za-z])/g,
            "$1 $2"
        )

        .replace(
            /\n{3,}/g,
            "\n\n"
        )

        .trim();

}


/* =========================================================
   IMPROVE TRANSITIONS
========================================================= */

function improveTransitions(
    text
) {

    const replacements = [

        {
            from:
                /^Furthermore,\s*/i,

            to:
                "Also, "
        },

        {
            from:
                /^Moreover,\s*/i,

            to:
                "Also, "
        },

        {
            from:
                /^In conclusion,\s*/i,

            to:
                "Overall, "
        },

        {
            from:
                /^In summary,\s*/i,

            to:
                "Overall, "
        },

        {
            from:
                /^It is important to note that\s*/i,

            to:
                ""
        },

        {
            from:
                /^It is worth noting that\s*/i,

            to:
                ""
        },

        {
            from:
                /^It should be noted that\s*/i,

            to:
                ""
        }

    ];


    const sentences =
        text.split(
            /(?<=[.!?])\s+/
        );


    return sentences
        .map(
            sentence => {

                for (
                    const replacement
                    of replacements
                ) {

                    sentence =
                        sentence.replace(
                            replacement.from,
                            replacement.to
                        );

                }


                return sentence;

            }
        )
        .join(" ");

}


/* =========================================================
   VARY REPEATED SENTENCE STARTS
========================================================= */

function varySentenceStarts(
    text
) {

    const sentences =
        text.split(
            /(?<=[.!?])\s+/
        );


    let previousStart =
        "";


    const alternatives = {

        "This": [

            "The idea",

            "This approach",

            "The concept"

        ],


        "These": [

            "Such",

            "Those",

            "These ideas"

        ],


        "The": [

            "This",

            "Another",

            "One"

        ]

    };


    return sentences

        .map(
            sentence => {

                const words =
                    sentence
                        .trim()
                        .split(/\s+/);


                if (
                    words.length < 5
                ) {

                    return sentence;

                }


                const start =
                    words[0];


                if (
                    start === previousStart &&
                    alternatives[start]
                ) {

                    const choices =
                        alternatives[
                            start
                        ];


                    const replacement =
                        choices[
                            Math.floor(
                                Math.random() *
                                choices.length
                            )
                        ];


                    words[0] =
                        replacement;


                    sentence =
                        words.join(
                            " "
                        );

                }


                previousStart =
                    start;


                return sentence;

            }
        )

        .join(" ");

}


/* =========================================================
   IMPROVE VERY LONG SENTENCES
========================================================= */

function improveLongSentences(
    text
) {

    const sentences =
        text.split(
            /(?<=[.!?])\s+/
        );


    return sentences

        .map(
            sentence => {

                const words =
                    sentence.split(
                        /\s+/
                    );


                /*
                   Only modify extremely long
                   sentences.
                */

                if (
                    words.length <= 45
                ) {

                    return sentence;

                }


                const commaIndex =
                    sentence.indexOf(
                        ","
                    );


                if (
                    commaIndex > 20 &&
                    commaIndex <
                    sentence.length - 20
                ) {

                    const first =
                        sentence.slice(
                            0,
                            commaIndex
                        );


                    const second =
                        sentence
                            .slice(
                                commaIndex + 1
                            )
                            .trim();


                    return (

                        first +

                        ". " +

                        second
                            .charAt(0)
                            .toUpperCase() +

                        second.slice(1)

                    );

                }


                return sentence;

            }
        )

        .join(" ");

}


/* =========================================================
   HUMANIZE TEXT
========================================================= */

function humanizeText(
    text
) {

    let result =
        text;


    /*
       STEP 1
       Clean spaces.
    */

    result =
        cleanSpacing(
            result
        );


    /*
       STEP 2
       Replace unnecessarily formal
       wording.
    */

    result =
        replaceFormalWords(
            result
        );


    /*
       STEP 3
       Improve transitions.
    */

    result =
        improveTransitions(
            result
        );


    /*
       STEP 4
       Reduce repetitive starts.
    */

    result =
        varySentenceStarts(
            result
        );


    /*
       STEP 5
       Handle extremely long sentences.
    */

    result =
        improveLongSentences(
            result
        );


    /*
       STEP 6
       Final cleanup.
    */

    result =
        cleanSpacing(
            result
        );


    return result;

}


/* =========================================================
   HUMANIZE BUTTON
========================================================= */

humanizeButton.addEventListener(
    "click",
    function() {

        const originalText =
            textInput.value.trim();


        if (
            !originalText
        ) {

            showError(
                "Please enter some text before using Humanize Text."
            );

            return;

        }


        if (
            countWords(
                originalText
            ) < 20
        ) {

            showError(
                "Please enter at least 20 words."
            );

            return;

        }


        errorBox.classList.add(
            "hidden"
        );


        humanizedSection.classList.add(
            "hidden"
        );


        loading.classList.remove(
            "hidden"
        );


        setTimeout(
            function() {

                try {

                    const humanized =
                        humanizeText(
                            originalText
                        );


                    humanizedText.value =
                        humanized;


                    humanizedSection
                        .classList
                        .remove(
                            "hidden"
                        );


                    humanizedSection
                        .scrollIntoView({

                            behavior:
                                "smooth",

                            block:
                                "start"

                        });

                }

                catch (error) {

                    console.error(
                        error
                    );


                    showError(
                        "Unable to humanize the text."
                    );

                }

                finally {

                    loading.classList.add(
                        "hidden"
                    );

                }

            },
            50
        );

    }
);


/* =========================================================
   COPY HUMANIZED TEXT
========================================================= */

copyButton.addEventListener(
    "click",
    async function() {

        const text =
            humanizedText.value;


        if (
            !text
        ) {

            return;

        }


        try {

            await navigator
                .clipboard
                .writeText(
                    text
                );


            copyButton.textContent =
                "Copied!";


            setTimeout(
                function() {

                    copyButton.textContent =
                        "Copy Text";

                },
                1500
            );

        }

        catch (error) {

            /*
               Fallback for older browsers.
            */

            humanizedText.select();


            document.execCommand(
                "copy"
            );


            copyButton.textContent =
                "Copied!";


            setTimeout(
                function() {

                    copyButton.textContent =
                        "Copy Text";

                },
                1500
            );

        }

    }
);


/* =========================================================
   USE HUMANIZED TEXT
========================================================= */

useHumanizedButton.addEventListener(
    "click",
    function() {

        if (
            !humanizedText.value
        ) {

            return;

        }


        /*
           Put humanized version back
           into the main editor.
        */

        textInput.value =
            humanizedText.value;


        /*
           Update counters.
        */

        updateCounters();


        /*
           Hide humanized section.
        */

        humanizedSection.classList.add(
            "hidden"
        );


        /*
           Automatically analyze
           the new version.
        */

        analyzeButton.click();


        /*
           Scroll back to editor.
        */

        textInput.scrollIntoView({

            behavior:
                "smooth",

            block:
                "center"

        });

    }
);


/* =========================================================
   CLEAR BUTTON
========================================================= */

clearButton.addEventListener(
    "click",
    function() {

        textInput.value =
            "";


        humanizedText.value =
            "";


        updateCounters();


        resultSection.classList.add(
            "hidden"
        );


        humanizedSection.classList.add(
            "hidden"
        );


        errorBox.classList.add(
            "hidden"
        );

    }
);


/* =========================================================
   ERROR FUNCTION
========================================================= */

function showError(
    message
) {

    errorBox.textContent =
        message;


    errorBox.classList.remove(
        "hidden"
    );


    resultSection.classList.add(
        "hidden"
    );

}


/* =========================================================
   UPDATE COUNTERS
========================================================= */

function updateCounters() {

    const text =
        textInput.value;


    const words =
        countWords(
            text
        );


    const characters =
        text.length;


    wordCount.textContent =
        words.toLocaleString();


    characterCount.textContent =
        characters.toLocaleString();

}


/* =========================================================
   LIVE COUNTER
========================================================= */

textInput.addEventListener(
    "input",
    updateCounters
);


/* =========================================================
   INITIALIZE WEBSITE
========================================================= */

updateCounters();
